server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springcloud-config.get #GitHub上面的git仓库的名字
          search-paths:
            -  springcloud-config
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
